---
version: "3.9"
services:

  wp:
    image: httpd:latest
    container_name: wp
    restart: unless-stopped

  py:
    build: build
    container_name: py
    volumes:
      - ./app/ping.py:/app/ping.py
    command: ["/app/ping.py"]
    restart: unless-stopped
    environment:
      - WP_HOSTNAME=wp

